name: 'Validate renovate config'
on:
  push:
    paths:
      - renovate.json
  pull_request:
    paths:
      - renovate.json

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --entrypoint bash -v "$PWD/renovate.json":/pwd/renovate.json renovate/renovate:slim renovate-config-validator /pwd/renovate.json
